/* Generated by `npm run import`. Do not edit.
   Edit the files in content/en2ja/ and re-run the script. */

import type { StoredExercise } from '../../schema';

export const GENERATED_EXERCISES: readonly StoredExercise[] = [
  {
    "id": "cafe-01",
    "scenarioId": "cafe",
    "promptText": "One coffee, please.",
    "answerTileIds": [
      "noun:コーヒー",
      "particle:を",
      "verb:ください"
    ],
    "alternateAnswerTileIds": [
      [
        "noun:コーヒー",
        "particle:を",
        "verb:お願いします"
      ]
    ],
    "note": "を marks the direct object — the thing you are ordering. Same frame as the bakery: ＸをＹください.",
    "tags": [
      "particle:を"
    ]
  },
  {
    "id": "cafe-02",
    "scenarioId": "cafe",
    "promptText": "Is this coffee hot?",
    "answerTileIds": [
      "demonstrative:この",
      "noun:コーヒー",
      "particle:は",
      "adjective:熱い",
      "ending:です",
      "particle:か"
    ],
    "alternateAnswerTileIds": [],
    "note": "この needs a noun after it. 熱い is already an adjective — です only adds politeness.",
    "tags": [
      "particle:は"
    ]
  },
  {
    "id": "cafe-03",
    "scenarioId": "cafe",
    "promptText": "I want to drink tea.",
    "answerTileIds": [
      "noun:紅茶",
      "particle:が",
      "verb:飲み",
      "ending:たい",
      "ending:です"
    ],
    "alternateAnswerTileIds": [],
    "note": "〜たい takes が for its object, not を. Attach たい to the verb stem: 飲み + たい.",
    "tags": [
      "particle:が",
      "conjugation:たい"
    ]
  },
  {
    "id": "cafe-04",
    "scenarioId": "cafe",
    "promptText": "Do you have milk?",
    "answerTileIds": [
      "noun:ミルク",
      "particle:は",
      "verb:あります",
      "particle:か"
    ],
    "alternateAnswerTileIds": [],
    "note": "For existence questions the item is the topic, so は. か turns the sentence into a question.",
    "tags": [
      "particle:は"
    ]
  },
  {
    "id": "cafe-05",
    "scenarioId": "cafe",
    "promptText": "Where is the restroom?",
    "answerTileIds": [
      "noun:トイレ",
      "particle:は",
      "question:どこ",
      "ending:です",
      "particle:か"
    ],
    "alternateAnswerTileIds": [],
    "note": "どこ stays where the answer would go — Japanese does not move question words to the front.",
    "tags": [
      "particle:は"
    ]
  }
];
