/* Generated by `npm run import`. Do not edit.
   Edit the files in content/en2ja/ and re-run the script. */

import type { StoredTile } from '../../schema';

export const GENERATED_TILES: readonly StoredTile[] = [
  {
    "id": "adjective:熱い",
    "scenarioIds": [
      "cafe"
    ],
    "newLanguageText": "熱い",
    "reading": "atsui",
    "type": "adjective"
  },
  {
    "id": "noun:紅茶",
    "scenarioIds": [
      "cafe"
    ],
    "newLanguageText": "紅茶",
    "reading": "koucha",
    "type": "noun"
  },
  {
    "id": "noun:ミルク",
    "scenarioIds": [
      "cafe"
    ],
    "newLanguageText": "ミルク",
    "reading": "miruku",
    "type": "noun"
  },
  {
    "id": "noun:トイレ",
    "scenarioIds": [
      "cafe"
    ],
    "newLanguageText": "トイレ",
    "reading": "toire",
    "type": "noun"
  }
];
